# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: 'curl --header $(HEADER) --data $(DATA) $(API) -o productrisk.pdf'
    displayName: '1233'

  - script: 'ls -al'
    displayName: 'ls'

  - script: 'curl -o page.pdf http://www.linuxidc.com'
    displayName: 'Get linux'
